# Generated by Django 5.2.5 on 2025-10-03 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProsodyTestDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textfield_prompts', models.TextField()),
                ('l1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosodytest_l1', to='testdefinition.language')),
                ('l2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosodytest_l2', to='testdefinition.language')),
            ],
        ),
        migrations.CreateModel(
            name='PreparationPhaseStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('prosody_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdefinition.prosodytestdefinition')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdefinition.teststage')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('prosody_test', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='ExperimentPhaseStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('prosody_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdefinition.prosodytestdefinition')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdefinition.teststage')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('prosody_test', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationPhaseStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('prosody_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdefinition.prosodytestdefinition')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdefinition.teststage')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('prosody_test', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent', models.BooleanField()),
                ('participant_name', models.CharField(max_length=100)),
                ('current_phase', models.CharField(choices=[('preparation', 'Preparation'), ('experiment', 'Experiment'), ('evaluation', 'Evaluation')], max_length=20)),
                ('current_stage_index', models.IntegerField()),
                ('recording', models.ManyToManyField(to='testdefinition.recording')),
            ],
        ),
        migrations.AddField(
            model_name='prosodytestdefinition',
            name='evaluation_phase',
            field=models.ManyToManyField(related_name='evaluation_phase', through='testdefinition.EvaluationPhaseStage', to='testdefinition.teststage'),
        ),
        migrations.AddField(
            model_name='prosodytestdefinition',
            name='experiment_phase',
            field=models.ManyToManyField(related_name='experiment_phase', through='testdefinition.ExperimentPhaseStage', to='testdefinition.teststage'),
        ),
        migrations.AddField(
            model_name='prosodytestdefinition',
            name='preparation_phase',
            field=models.ManyToManyField(related_name='preparation_phase', through='testdefinition.PreparationPhaseStage', to='testdefinition.teststage'),
        ),
    ]
