# Generated by Django 5.2.5 on 2025-10-03 12:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdefinition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrun',
            name='used_test_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='testdefinition.prosodytestdefinition'),
        ),
    ]
