# Generated by Django 5.2.5 on 2025-10-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdefinition', '0003_testrun_experiment_prompt_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prosodytestdefinition',
            old_name='textfield_prompts',
            new_name='prompts',
        ),
    ]
