# Generated by Django 5.2.5 on 2025-11-07 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdefinition', '0004_rename_textfield_prompts_prosodytestdefinition_prompts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrun',
            name='recording',
        ),
        migrations.AddField(
            model_name='recording',
            name='testrun',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='testdefinition.testrun'),
            preserve_default=False,
        ),
    ]
