# Generated by Django 5.2.5 on 2025-11-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdefinition', '0005_remove_testrun_recording_recording_testrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prosodytestdefinition',
            name='prompts',
        ),
        migrations.AddField(
            model_name='prosodytestdefinition',
            name='target_prompts',
            field=models.TextField(blank=True, help_text='Prompts for the main test (one per line)', null=True),
        ),
        migrations.AddField(
            model_name='prosodytestdefinition',
            name='trial_prompts',
            field=models.TextField(blank=True, help_text='Prompts for the trial/field test (one per line)', null=True),
        ),
    ]
