# Generated by Django 5.2.5 on 2025-11-14 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdefinition', '0006_remove_prosodytestdefinition_prompts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preparationphasestage',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='preparationphasestage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='prosodytestdefinition',
            name='experiment_phase',
        ),
        migrations.CreateModel(
            name='MainTestPhaseStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('prosody_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdefinition.prosodytestdefinition')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdefinition.teststage')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('prosody_test', 'stage')},
            },
        ),
        migrations.AddField(
            model_name='prosodytestdefinition',
            name='main_test_phase',
            field=models.ManyToManyField(related_name='main_test_phase', through='testdefinition.MainTestPhaseStage', to='testdefinition.teststage'),
        ),
    ]
