# Generated by Django 5.2.5 on 2025-11-28 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdefinition', '0008_trialtestphasestage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prosodytestdefinition',
            name='l1',
        ),
        migrations.AddField(
            model_name='testrun',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='l1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testrun_l1', to='testdefinition.language'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='current_phase',
            field=models.CharField(choices=[('preparation', 'Preparation'), ('trial', 'Trial'), ('main', 'Main'), ('evaluation', 'Evaluation')], max_length=20),
        ),
    ]
