# Generated by Django 5.2.5 on 2025-11-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdefinition', '0009_remove_prosodytestdefinition_l1_testrun_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='l1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
