# Generated by Django 5.2.5 on 2026-01-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdefinition', '0010_alter_testrun_l1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrialTestPhaseStage',
            new_name='PractiseTestPhaseStage',
        ),
        migrations.RemoveField(
            model_name='prosodytestdefinition',
            name='trial_prompts',
        ),
        migrations.RemoveField(
            model_name='prosodytestdefinition',
            name='trial_test_phase',
        ),
        migrations.AddField(
            model_name='prosodytestdefinition',
            name='practise_prompts',
            field=models.TextField(blank=True, help_text='Prompts for the practise/field test (one per line)', null=True),
        ),
        migrations.AddField(
            model_name='prosodytestdefinition',
            name='practise_test_phase',
            field=models.ManyToManyField(related_name='practise_test_phase', through='testdefinition.PractiseTestPhaseStage', to='testdefinition.teststage'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='current_phase',
            field=models.CharField(choices=[('preparation', 'Preparation'), ('practise', 'Practise'), ('main', 'Main'), ('evaluation', 'Evaluation')], max_length=20),
        ),
    ]
