# Generated by Django 5.2.5 on 2026-01-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdefinition', '0011_rename_trialtestphasestage_practisetestphasestage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prosodytestdefinition',
            name='practise_prompts',
        ),
        migrations.RemoveField(
            model_name='prosodytestdefinition',
            name='target_prompts',
        ),
        migrations.AddField(
            model_name='prosodytestdefinition',
            name='main_trials',
            field=models.TextField(blank=True, help_text='Trials for the main test (one per line), separate context and prompt with |', null=True),
        ),
        migrations.AddField(
            model_name='prosodytestdefinition',
            name='practise_trials',
            field=models.TextField(blank=True, help_text='Trials for the practise test (one per line), separate context and prompt with |', null=True),
        ),
    ]
