# Generated by Django 5.2.5 on 2026-01-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdefinition', '0013_rename_experiment_prompt_index_testrun_experiment_trial_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording',
            old_name='prompt',
            new_name='trial',
        ),
    ]
