# Generated by Django 5.2.5 on 2026-01-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdefinition', '0014_rename_prompt_recording_trial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrun',
            name='participant_name',
        ),
    ]
