# Generated by Django 5.2.5 on 2026-01-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdefinition', '0015_remove_testrun_participant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='main_trial_order',
            field=models.TextField(blank=True, null=True),
        ),
    ]
