# Generated by Django 5.2.5 on 2026-01-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdefinition', '0017_testrun_age_testrun_asd_testrun_birth_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrun',
            name='country',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='l1',
        ),
        migrations.AlterField(
            model_name='testrun',
            name='asd',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('prefer not to say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='dyslexia',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('prefer not to say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='education',
            field=models.CharField(blank=True, choices=[('no formal education', 'No formal education'), ('primary school', 'Primary school'), ('secondary school', 'Secondary school'), ('Technical/Community College', 'Technical/Community College'), ('University', 'University'), ('prefer not to say', 'Prefer not to say')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='learning_impairment',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('prefer not to say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='other_languages',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
