# Generated by Django 5.2.5 on 2026-03-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdefinition', '0018_remove_testrun_country_remove_testrun_l1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='english_reading_proficiency',
            field=models.CharField(blank=True, choices=[('a1 beginner', 'A1 beginner'), ('a2 beginner', 'A2 beginner'), ('b1 intermediate', 'B1 intermediate'), ('b2 intermediate', 'B2 intermediate'), ('c1 proficient', 'C1 proficient'), ('c2 proficient', 'C2 proficient')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='english_speaking_proficiency',
            field=models.CharField(blank=True, choices=[('a1 beginner', 'A1 beginner'), ('a2 beginner', 'A2 beginner'), ('b1 intermediate', 'B1 intermediate'), ('b2 intermediate', 'B2 intermediate'), ('c1 proficient', 'C1 proficient'), ('c2 proficient', 'C2 proficient')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='english_type',
            field=models.CharField(blank=True, choices=[('british', 'British'), ('american', 'American'), ('australian', 'Australian'), ('other', 'Other'), ('i do not know', "I don't know")], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='english_writing_proficiency',
            field=models.CharField(blank=True, choices=[('a1 beginner', 'A1 beginner'), ('a2 beginner', 'A2 beginner'), ('b1 intermediate', 'B1 intermediate'), ('b2 intermediate', 'B2 intermediate'), ('c1 proficient', 'C1 proficient'), ('c2 proficient', 'C2 proficient')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='home_languages_growing_up',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='live_now_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
